# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Project Portfolio
email: tdlam112796@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Small webpage project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.tl7td.me" # the base hostname & protocol for your site
twitter_username: _TommyDL_
github_username:  tl7td

# Build settings
markdown: kramdown
